// http статусы
const SUCCESS_STATUS_OK = 200;
const SUCCESS_STATUS_CREATED = 201;
const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const CONFLICT_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;
const DUPLICATION_ERROR = 11000;

// сообщения
const USER_BAD_REQUEST_ERROR_MESSAGE = 'При обновлении профиля произошла ошибка';
const VALIDATION_ERROR_MESSAGE = 'Невалидные данные';
const UNAUTHORIZED_ERROR_MESSAGE = 'Необходима авторизация';
const INCORRECT_USERDATA_MESSAGE = 'Неправильные почта или пароль';
const DELETE_MOVIE_FORBIDDEN_ERROR_MESSAGE = 'Нельзя удалить чужой фильм';
const USER_NOT_FOUND_ERROR_MESSAGE = 'Пользователь не найден';
const MOVIE_NOT_FOUND_ERROR_MESSAGE = 'Фильм не найден';
const INTERNAL_SERVER_ERROR_MESSAGE = 'На сервере произошла ошибка';
const SUCCESSFUL_LOGIN_MESSAGE = 'Успешная авторизация';
const SUCCESSFUL_LOGOUT_MESSAGE = 'Выход из аккаунта';
const AUTHORIZATION_NOT_FOUND_USER_ERROR_MESSAGE = 'Вы ввели неправильный логин или пароль.';
const AUTHORIZATION_NOT_FOUND_TOKEN_ERROR_MESSAGE = 'При авторизации произошла ошибка. Токен не передан или передан не в том формате.';
const AUTHORIZATION_INVALID_TOKEN_ERROR_MESSAGE = 'При авторизации произошла ошибка. Переданный токен некорректен.';
const REGISTER_BAD_REQUEST_ERROR_MESSAGE = 'При регистрации пользователя произошла ошибка';
const REGISTER_EMAIL_DUPLICATION_ERROR_MESSAGE = 'Пользователь с таким email уже существует';
const USER_DUPLICATION_ERROR_MESSAGE = 'Пользователь с таким email уже существует';

module.exports = {
  AUTHORIZATION_NOT_FOUND_USER_ERROR_MESSAGE,
  AUTHORIZATION_NOT_FOUND_TOKEN_ERROR_MESSAGE,
  AUTHORIZATION_INVALID_TOKEN_ERROR_MESSAGE,
  REGISTER_BAD_REQUEST_ERROR_MESSAGE,
  REGISTER_EMAIL_DUPLICATION_ERROR_MESSAGE,
  USER_DUPLICATION_ERROR_MESSAGE,
  USER_BAD_REQUEST_ERROR_MESSAGE,
  VALIDATION_ERROR_MESSAGE,
  UNAUTHORIZED_ERROR_MESSAGE,
  INCORRECT_USERDATA_MESSAGE,
  DELETE_MOVIE_FORBIDDEN_ERROR_MESSAGE,
  USER_NOT_FOUND_ERROR_MESSAGE,
  MOVIE_NOT_FOUND_ERROR_MESSAGE,
  INTERNAL_SERVER_ERROR_MESSAGE,
  SUCCESSFUL_LOGIN_MESSAGE,
  SUCCESSFUL_LOGOUT_MESSAGE,
  SUCCESS_STATUS_OK,
  SUCCESS_STATUS_CREATED,
  BAD_REQUEST_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  CONFLICT_ERROR,
  INTERNAL_SERVER_ERROR,
  DUPLICATION_ERROR,
};
